config/routes.rb
FootballRails::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "login", :to => "devise/sessions#new"
    delete "logout", to: "devise/sessions#destroy"
    get "signup", to: "devise/registrations#new"
  end

  resources :teams

  resources :seasons do
    resources :weeks do
      get 'picks', to: "picks#index"
      resources :matches do
        resources :picks do #without picks#index
        end
      end
    end
  end

  root to: 'seasons#index'
end

app/models/week.rb
class Week < ActiveRecord::Base
  attr_accessible :number, :start_time, :end_time
  belongs_to :season

  has_many :matches
  has_many :picks

  def to_param
    id
  end

  def current_winner
    User.all.sort_by{|user| user.points_by_week(id)}.first
  end

  def winning_teams
    @teams = []
    matches.map {|match| @teams << match.winner }
    @teams
  end

end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController

  def index
    @weeks = current_season.weeks.all
  end

  def show
    @week = current_season.weeks.find(params[:id])
    @picks = current_user.picks.all if current_user
  end

  def new
    @week = current_season.weeks.new
  end

  def edit
    @week = current_season.weeks.find(params[:id])
  end

  def create
    @week = current_season.weeks.new(params[:week])

    if @week.save
      redirect_to [current_season, @week], notice: 'Week was successfully created.' 
    else
      render action: "new" 
    end
  end

  def update
    @week = current_season.weeks.find(params[:id])

    if @week.update_attributes(params[:week])
      redirect_to [current_season, @week], notice: 'Week was successfully updated.' 
    else
      format.html render action: "edit" 
    end
  end

  def destroy
    @week = current_season.weeks.find(params[:id])
    
    if @week.destroy
      redirect_to season_weeks_path 
    end
  end

private

  def current_season
    @current_season = Season.find(params[:season_id])
  end
  helper_method :current_season

  def current_week
    @current_week = current_season.weeks.find(params[:id]) if params[:id]
  end
  helper_method :current_week 
end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/views/weeks/_form.html.erb
<%= form_for [current_season, @week] do |f| %>
  <% if @week.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@week.errors.count, "error") %> prohibited this week from being saved:</h2>

      <ul>
      <% @week.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br />
    <%= f.select :number, (1..17) %>
  </div>
    <div class="field">
    <p>This is when people can start adding picks</p>
    <%= f.label :start_time %><br />
    <%= f.datetime_select :start_time %>
  </div>
    <div class="field">
    <p>After this time, users can no longer enter or change their picks</p>
    <%= f.label :end_time %><br />
    <%= f.datetime_select :end_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %> 

app/views/weeks/edit.html.erb
<h1>Editing week</h1>

<%= render 'form' %>

<%= link_to 'Show', [current_season, @week] %> |
<%= link_to 'Back', season_weeks_path(current_season) %>

app/views/weeks/index.html.erb
<h1>Listing weeks</h1>

<table>
  <tr>
    <th>Number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @weeks.each do |week| %>
  <tr>
    <td><%= week.number %></td>
    <td><%= link_to 'Show', [current_season, week] %></td>
    <td><%= link_to 'Edit', edit_season_week_path(current_season, week) %></td>
    <td><%= link_to 'Destroy', [current_season, week], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Week', new_season_week_path(current_season) %>

app/views/weeks/new.html.erb
<h1>New week</h1>

<%= render 'form' %>

<%= link_to 'Back', season_weeks_path(current_season) %>

app/views/weeks/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <b>Week </b>
  <%= @week.number %>
</h1>

<table>
<% @week.matches.each do |match| %>
  <tr>
    <td><%= match.home_team.name %></td>
    <td><%= match.away_team.name %></td>
    <% if user_signed_in? %>
      <% if match.pick_for_user(current_user).present? %>
        <td><%= link_to "Edit your pick", edit_season_week_match_pick_path(current_season, @week, match, match.pick_for_user(current_user)) %></td>
        <td>(You put <%= match.pick_for_user(current_user).value %> on <%= match.pick_for_user(current_user).team_picked.name %>)</td>  
      <% else %>
        <td><%= link_to "Put points on this match", new_season_week_match_pick_path(current_season, @week, match) %></td>
      <% end %>
    <% end %>
  </tr>
<% end %>
</table>

<p>
  <%= link_to 'New Match', new_season_week_match_path(current_season, @week) %>
</p>

<%= link_to 'Edit', edit_season_week_path(current_season, @week) %> |
<%= link_to 'Back', season_weeks_path %>