config/routes.rb
FootballRails::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "login", :to => "devise/sessions#new"
    delete "logout", to: "devise/sessions#destroy"
    get "signup", to: "devise/registrations#new"
  end

  resources :teams

  resources :seasons do
    resources :weeks do
      get 'picks', to: "picks#index"
      resources :matches do
        resources :picks do #without picks#index
        end
      end
    end
  end

  root to: 'seasons#index'
end

app/models/match.rb
class Match < ActiveRecord::Base
  # attr_accessible 
  belongs_to :week
  belongs_to :season
  has_many :picks, dependent: :destroy

  belongs_to :home_team, class_name: "Team"
  belongs_to :away_team, class_name: "Team"

  attr_accessible :home_team_score, :away_team_score, :kickoff_time, :home_team_id, :away_team_id

  validate do 
    teams_must_be_different
  end

  def to_param
    id
  end

  def pick_for_user user
    user.picks.where(match_id: id).first
  end

  def winner
    if home_team_score.present? && away_team_score.present?
      if home_team_score > away_team_score
        @winner = home_team
      end
      if away_team_score > home_team_score
        @winner = away_team
      end
    end
    #TODO figure out ties
    @winner
  end

  def teams_must_be_different
    if home_team.present? && away_team.present?
      if home_team == away_team
        errors.add(:base, "The two competing teams in this game must be different!")
      end
    end
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  def index
    @matches = current_week.matches.all
  end

  def show
    @match = current_week.matches.find(params[:id])
  end

  def new
    @match = current_week.matches.new
  end

  def edit
    @match = current_week.matches.find(params[:id])
  end

  def create
    @match = current_week.matches.new(params[:match])

    if @match.save
      redirect_to [current_season, current_week, @match], notice: 'Match was successfully created.' 
    else
      render action: "new"
    end
  end

  def update
    @match = current_week.matches.find(params[:id])

    if @match.update_attributes(params[:match])
      redirect_to [current_season, current_week, @match], notice: 'Match was successfully updated.' 
    else
      render action: "edit" 
    end
  end

  def destroy
    @match = current_week.matches.find(params[:id])
    @match.destroy

    redirect_to season_week_path(current_season, current_week)
  end

  private

  def current_season
    @current_season = Season.find(params[:season_id])
  end
  helper_method :current_season

  def current_week
    @current_week = current_season.weeks.find(params[:week_id])
  end
  helper_method :current_week
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_for([current_season, current_week, @match]) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    Home Team
    <div class="field">
      <%= collection_select :match, :home_team_id, Team.all, :id, :name, { :selected => @match.home_team } %>
    </div>

    Away Team
    <div class="field">
      <%= collection_select :match, :away_team_id, Team.all, :id, :name, { :selected => @match.away_team } %>
    </div>

    Kick-off Time
    <div class="field">
      <%= f.datetime_select :kickoff_time %>
    </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing match</h1>

<%= render 'form' %>

<%= link_to 'Show', [current_season, current_week, @match] %> |
<%= link_to 'Back', season_week_matches_path(current_season, current_week) %>

app/views/matches/index.html.erb
<h1>Listing matches</h1>

<table>
  <tr>
    <th>Season</th>
    <th>Week</th>
    <th>Home Team</th>
    <th>Away Team</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @matches.each do |match| %>
  <tr>
    <td><%= match.season_id %></td>
    <td><%= match.week_id %></td>
    <td>
      <% if match.winner == match.home_team %>
        <span class="winner"><%= match.home_team.name %></span>
      <% else %>
        <%= match.home_team.name %>
      <% end %>
    </td>
        <td>
      <% if match.winner == match.away_team %>
        <span class="winner"><%= match.away_team.name %></span>
      <% else %>
        <%= match.away_team.name %>
      <% end %>
    </td>
    <td><%= link_to 'Show', season_week_match_path(current_season, current_week, match) %></td>
    <td><%= link_to 'Edit', edit_season_week_match_path(current_season, current_week, match) %></td>
    <td><%= link_to 'Destroy', season_week_match_path(current_season, current_week, match), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Match', new_season_week_match_path(current_season, current_week) %>

app/views/matches/new.html.erb
<h1>New match</h1>

<%= render 'form' %>

<%= link_to 'Back', season_week_matches_path(current_season, current_week) %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Season:</b>
  <%= @match.season_id %>
</p>

<p>
  <b>Week:</b>
  <%= @match.week_id %>
</p>

<% if current_user && current_user.has_role(:admin) %>
  <h3>Assign final scores to this match:</h3>

  <%= form_for [current_season, current_week, @match] do |f| %>
    <%= f.label "#{@match.home_team.name} final score: " %>
    <%= f.text_field :home_team_score %>
    <br>
    <%= f.label "#{@match.away_team.name} final score: " %>
    <%= f.text_field :away_team_score %>
    <br>
    <%= f.submit "Submit Score" %>
  <% end %>
<% end %> 

<%= link_to 'Edit', edit_season_week_match_path(@match) %> |
<%= link_to 'Back', season_week_matches_path %>